//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAidAllocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amount
    {
        public int Id { get; set; }
        public Nullable<int> first_position { get; set; }
        public Nullable<int> second_position { get; set; }
        public Nullable<int> third_position { get; set; }
        public string session { get; set; }
    }
}
