//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAidAllocation.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FeedBack
    {
        public int id { get; set; }
        public Nullable<int> feedback1 { get; set; }
        public string semester { get; set; }
        public int graderId { get; set; }
        public int facultyID { get; set; }
        [JsonIgnore]

        public virtual Grader Grader { get; set; }
    }
}
