//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAidAllocation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialAid
    {
        public int id { get; set; }
        public int applicationId { get; set; }
        public string amount { get; set; }
        public string applicationStatus { get; set; }
        public string aidtype { get; set; }
        public Nullable<int> position { get; set; }
    }
}
