//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialAidAllocation.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Grader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grader()
        {
            this.FeedBacks = new HashSet<FeedBack>();
        }
    
        public int id { get; set; }
        public int facultyId { get; set; }
        public string session { get; set; }
        public int studentId { get; set; }
        public Nullable<int> feedback { get; set; }
        [JsonIgnore]

        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        [JsonIgnore]
        public virtual Student Student { get; set; }
    }
}
